version: '2'
services:
  postgreshost:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "uwsgi --socket 0.0.0.0:3000 --protocol=http --module django_waitlist.wsgi --master --pidfile=/tmp/project-master.pid --processes=1 --enable-threads --static-map /static=/code/static"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    links:
      - postgreshost

  tcell_web:
    build: .
    command: sh -c "pip install -r requirements.txt && tcell_agent run uwsgi --socket 0.0.0.0:3000 --protocol=http --module django_waitlist.wsgi --master --pidfile=/tmp/project-master.pid --processes=1 --enable-threads --static-map /static=/code/static"
    volumes:
      - .:/code
      - ./requirements.tcell.txt:/code/requirements.txt
    ports:
      - "3000:3000"
    links:
      - postgreshost

  tcell_local_web:
    build: .
    command: sh -c "pip install -e /tcellagent_src && tcell_agent run uwsgi --socket 0.0.0.0:3000 --protocol=http --module django_waitlist.wsgi --master --pidfile=/tmp/project-master.pid --processes=1 --enable-threads --static-map /static=/code/static"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/code
      - ./requirements.tcell.local.txt:/code/requirements.txt
    ports:
      - "3000:3000"
    links:
      - postgreshost
